- name: Create .vimrc symlinks
  file:
    src: '{{ ubuntu_mnt }}/.vimrc'
    dest: ~/.vimrc
    state: link
    force: yes

- name: Create .vim-snippets symlinks
  file:
    src: '{{ common_mnt }}/.vim-snippets'
    dest: ~/.vim-snippets
    state: link
    force: yes
