- name: Vim
  file:
    src: '{{ ubuntu_mnt }}/.ideavimrc'
    dest: ~/.ideavimrc
    state: link
    force: yes

- name: Directory link
  file:
    src: '~/{{ intellij_dir }}'
    dest: ~/{{ intellij_fix_dir }}
    state: link
    force: yes

- name: Create directories for links
  file:
    path: ~/{{ intellij_fix_dir }}/{{ item }}
    state: directory
    mode: 0775
  with_items:
    - config/colors
    - config/keymaps

- name: Create symlinks
  file:
    src: '{{ ubuntu_mnt }}/{{ intellij_fix_dir }}/{{ item }}'
    dest: ~/{{ intellij_fix_dir }}/{{ item }}
    state: link
    force: yes
  with_items:
    - config/colors/mamansoft.icls
    - config/keymaps/mamansoft.xml
    - config/options/editor.xml
    - config/options/colors.scheme.xml
    - config/options/ide.general.xml
    - config/options/keymap.xml
    - config/options/markdown.xml
    - config/options/vcs.xml
    - config/templates
