- name: Install dependencies
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
  update_cache: yes
  with_items:
    # pyenv
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

