- name: Install dependencies
  become: yes
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    # pyenv
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    # tmux
    - automake
    - libevent-dev

- name: Clone powerline font
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/fonts
    depth: 1

- name: Install powerline font
  command: ./install.sh
  args:
    chdir: /tmp/fonts

