- name: Install dependencies
  become: yes
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    # pyenv
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - ntp
    # tmux
    - automake
    - libevent-dev
    # migemo
    - cmigemo

- name: Set LC_ALL
  lineinfile:
    path: ~/.bashrc
    line: 'export LC_ALL=en_US.UTF8'

