- name: Install
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: /usr/bin/diff-so-fancy
    mode: u+x,g+x,o+x

- name: Set gitconfig
  git_config:
    name: '{{ item.key }}'
    scope: global
    value: '{{ item.value }}'
  with_items:
    - key: core.pager
      value: "diff-so-fancy | less --tabs=4 -RFX"
    - key: color.ui
      value: true
    - key: color.diff-highlight.oldNormal
      value: "red bold"
    - key: color.diff-highlight.oldHighlight
      value: "red bold 52"
    - key: color.diff-highlight.newNormal
      value: "green bold"
    - key: color.diff-highlight.newHighlight
      value: "green bold 22"
    - key: color.diff.meta
      value: "yellow"
    - key: color.diff.frag
      value: "magenta bold"
    - key: color.diff.commit
      value: "yellow bold"
    - key: color.diff.old
      value: "red bold"
    - key: color.diff.new
      value: "green bold"
    - key: color.diff.whitespace
      value: "red reverse"
