- import_role: { name: check/absent }
  vars:
    target: npm
    command: "npm --version | grep -E ^6"

- import_tasks: install.yml
  when: npm_is_absent

- name: Add to loading n
  lineinfile:
    path: ~/.bashrc
    line: 'export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).'
