- name: Add Git repository
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa

- name: Install Git
  become: yes
  apt:
    name: git
    update_cache: yes
    state: latest

- name: Install tig
  become: yes
  apt:
    name: tig
    update_cache: yes
    state: latest

