- name: "[GitKraken] Download .deb package"
  become: yes
  get_url:
    url: https://release.gitkraken.com/linux/gitkraken-amd64.deb
    dest: /tmp/gitkraken.deb

- name: "[GitKraken] Install"
  become: yes
  apt:
    deb: /tmp/gitkraken.deb

