- name: "[Hugo] Install"
  become: yes
  unarchive:
    src: https://github.com/gohugoio/hugo/releases/download/v{{ version }}/hugo_{{ version }}_Linux-64bit.tar.gz
    dest: /usr/bin
    mode: u+x,g+x,o+x
    remote_src: yes
    creates: /usr/bin/hugo
  
