- import_tasks: unzip.yml
- import_tasks: hugo.yml
- import_tasks: nkf.yml
- import_tasks: jq.yml
- import_tasks: xmllint.yml
- import_tasks: icdiff.yml
  tags: engsvr
- import_tasks: tree.yml
- import_tasks: awscli.yml
- import_tasks: tig.yml
  tags: engsvr
  vars:
    version: 2.3.0  
- import_tasks: pt.yml
  tags: engsvr

