- name: Install The Platinum Search
  become: yes
  get_url:
    url: https://github.com/monochromegane/the_platinum_searcher/releases/download/v2.1.5/pt_linux_amd64.tar.gz
    dest: /usr/bin/pt
    mode: u+x,g+x,o+x

