- name: "[Platinum Searcher] Install"
  become: yes
  block:
    - unarchive:
        src: https://github.com/monochromegane/the_platinum_searcher/releases/download/v{{ version }}/pt_linux_amd64.tar.gz
        dest: /tmp
        mode: u+x,g+x,o+x
        remote_src: yes
        creates: /usr/bin/pt
    - shell: mv /tmp/pt_linux_amd64/pt /usr/bin/pt
      args:
        creates: /usr/bin/pt
