- name: Directory link
  file:
    src: '{{ intellij_dir }}'
    dest: '~/{{ intellij_fix_dir }}'
    state: link
    force: yes

- name: Create config symlinks
  file:
    src: '{{ common_mnt }}/{{ intellij_fix_dir }}/config/{{ item }}'
    dest: '~/{{ intellij_fix_dir }}/{{ item }}'
    state: link
    force: yes
  with_items:
    - colors
    - keymaps
    - templates
    - codestyles
    - inspection

- name: Create options symlinks
  file:
    src: '{{ common_mnt }}/{{ intellij_fix_dir }}/config/options/{{ item }}'
    dest: '~/{{ intellij_fix_dir }}/options/{{ item }}'
    state: link
    force: yes
  with_items:
    - editor.xml
    - colors.scheme.xml
    - ide.general.xml
    - keymap.xml
    - markdown.xml
    - vcs.xml
    - code.style.schemes.xml
    - project.default.xml
    - ui.lnf.xml
    - watcherDefaultTasks.xml

- name: Vim
  file:
    src: '{{ common_mnt }}/{{ intellij_fix_dir }}/.ideavimrc'
    dest: ~/.ideavimrc
    state: link
    force: yes

