- name: Add fish repository from PPA and install its signing key.
  become: yes
  apt_repository:
    repo: 'ppa:fish-shell/release-2'

- name: Install fish
  become: yes
  apt:
    name: fish
    update_cache: yes
    state: latest
