- name: "[tmux] Clone"
  git:
    repo: https://github.com/tmux/tmux.git
    dest: /tmp/tmux

- name: "[tmux] Install"
  shell: '{{ item }}'
  become: yes
  args:
    chdir: /tmp/tmux
    creates: /usr/local/bin/tmux
  with_items:
    - ./autogen.sh
    - ./configure
    - make
    - make install

- name: "[tmux] Install tmux-theme"
  shell: git clone --depth 1 https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
  args:
    creates: ~/.tmux-themepack
  tags: tmp

