- name: "[Powerline] Check"
  shell: 'ls ~/.local/share/fonts/*Powerline*'
  failed_when: no
  changed_when: no
  register: result

- name: "[Powerline] Clone font"
  when: result.rc
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/fonts
    depth: 1

- name: "[Powerline] Install"
  when: result.rc
  shell: ./install.sh
  args:
    chdir: /tmp/fonts

