- name: "[VS Code] Check already installed"
  stat:
    path: /usr/bin/code
  register: vscode_installed

- name: "[VS Code] Install"
  when: not vscode_installed.stat.exists
  become: yes
  block:
    - get_url:
        url: https://go.microsoft.com/fwlink/?LinkID=760868
        dest: /tmp/vscode.deb
    - apt:
        deb: /tmp/vscode.deb
    - command: apt-get install -f

