- import_role: { name: check/absent }
  vars:
    target: fzf
    command: 'fzf --version'

- import_tasks: install.yml
  when: fzf_is_absent

- name: Add to loading fzf
  lineinfile:
    path: ~/.bashrc
    line: '[ -f ~/.fzf.bash ] && source ~/.fzf.bash'
