- name: Install
  unarchive:
    src: https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install
  shell: mv ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl/rg /usr/bin/rg
  args:
    chdir: /tmp
