return {
  dir = "~/git/github.com/tadashi-aikawa/ghostwriter.nvim",
  ft = "markdown",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
  },
  keys = {
    { "gsw", ":GhostwriterWrite<CR>", silent = true },
    { "gsp", ":GhostwriterPost ", mode = { "v" } },
    { "gsm", ":GhostwriterRecentMessages" },
    { "gsy", ":GhostwriterCopy<CR>", mode = { "v" }, silent = true },
  },
  opts = {
    replacers = {
      { pattern = " %[%[202%d+_", replaced = " [[" },
      { pattern = " %[%[MTG_202%d+_", replaced = " [[📅 " },
      { pattern = " %[%[MTG_", replaced = " [[📅 " },
      { pattern = " 202%d+_", replaced = " " },
      { pattern = " MTG_202%d+_", replaced = " 📅 " },
      { pattern = " MTG_", replaced = " 📅 " },
      { pattern = "%d%d:%d%d ([^📅][^📅][^📅][^📅].*)$", replaced = "%1" },
      { pattern = "``$", replaced = "" },
      { pattern = "` (%d%d:%d%d:%d%d)`$", replaced = "`🕓%1`" },
      { pattern = "^%| 9f", replaced = ":vertical-line::to9f:" },
      { pattern = "^%| 8f", replaced = ":vertical-line::to8f:" },
      { pattern = "^%| 7f", replaced = ":vertical-line::to7f:" },
      { pattern = "^%| 6f", replaced = ":vertical-line::to6f:" },
      { pattern = "^%| 2f", replaced = ":vertical-line::to2f:" },
      { pattern = "^%| 1f", replaced = ":vertical-line::to1f:" },
      { pattern = "^%|", replaced = ":vertical-line:" },
      { pattern = "@cw", replaced = ":office:" },
      { pattern = "@zzz", replaced = ":busdataman_sleep_face:" },
      { pattern = "@study", replaced = ":mimizou:" },
      { pattern = "@jh", replaced = ":biznavi:" },
      { pattern = "@data", replaced = ":datapj:" },
      { pattern = "@ds", replaced = ":devsupport:" },
      { pattern = "@qmo", replaced = ":shield:" },
      { pattern = "@ts", replaced = ":typescript2:" },
      { pattern = "@nac", replaced = ":nac:" },
      { pattern = "@navi", replaced = ":ntc:" },
      { pattern = "@note", replaced = ":note_logo:" },
    },
    check = {
      { mark = "~", emoji = "loading" },
      { mark = "x", emoji = "ok_green" },
      { mark = "_", emoji = "circle_to_be_continued" },
      { mark = "-", emoji = "circle-failure" },
      { mark = " ", emoji = "circle-success" },
    },
    channel = {
      { name = "times", id = "C1J80C5MF" },
      { name = "task", id = "C06J0RG1V2L" },
      { name = "jh", id = "C072W42TPR7" },
      { name = "info_jh", id = "C06HXFVFZ4M" },
      { name = "vim", id = "C8NFWKY56" },
      { name = "ts", id = "C8K77FCH2" },
    },
  },
}
