- name: "[rls-preview] Install"
  shell: ~/.cargo/bin/rustup component add rls-preview

- name: "[rust-analysis] Install"
  shell: ~/.cargo/bin/rustup component add rust-analysis

- name: "[rust-src] Install"
  shell: ~/.cargo/bin/rustup component add rust-src

- name: "[rustfmt] Install"
  shell: ~/.cargo/bin/rustup component add rustfmt-preview
