- name: "[Nerd Fonts] Clone font"
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/fonts
    depth: 1

- name: "[Nerd Fonts] Install"
  shell: ./install.sh SourceCodePro
  args:
    chdir: /tmp/fonts

