default_flags = "g"

[[verbs]]
invocation = "edit"
key = "shift-enter"
internal = ":open_stay"

[[verbs]]
invocation = "vim"
key = "enter"
external = "vim {file}"
leave_broot = false
apply_to = "file"

[[verbs]]
invocation = "preview"
key = "ctrl-p"
internal = "toggle_preview"
apply_to = "file"

[[verbs]]
invocation = "cd"
key = "ctrl-enter"
external = "cd {directory}"
from_shell = true
