- import_role: { name: check/absent }
  vars:
    target: delta
    command: 'delta --version | grep "delta {{ delta_version }}"'

- import_tasks: install.yml
  when: delta_is_absent
  become: yes

- name: Set gitconfig
  git_config:
    name: '{{ item.key }}'
    scope: global
    value: '{{ item.value }}'
  with_items:
    - key: core.pager
      value: "delta"
    - key: core.whitespace
      value: "cr-at-eol"
    - key: delta.syntax-theme
      value: "Monokai Extended"
    - key: delta.line-number
      value: "true"
    - key: delta.side-by-side
      value: "true"
    - key: interactive.diffFilter
      value: "delta --color-only"

