- name: '[umake] Add repository'
  become: yes
  apt_repository:
    repo: ppa:ubuntu-desktop/ubuntu-make

- name: '[umake] Install'
  become: yes
  apt:
    name: ubuntu-make

- set_fact:
    umake: true

