# --------------------------------------
# ❢ It must not include `-` in target
# --------------------------------------
- name: "Check if {{ target }} is absent"
  shell: "{{ command }}"
  failed_when: no
  changed_when: no
  register: check

- set_fact:
    "{{ target }}_is_absent": '{{ check.rc != 0 }}'
