pipeline {
    agent { label 'master' }

    parameters {
        string(
            name: 'PARAMETER',
            defaultValue: 'default parameter',
            description: 'parameter description',
        )
    }

    options {
        buildDiscarder(
            logRotator(
                numToKeepStr: '10'
            )
        )
    }

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Fetch AccessLog') {
            environment {
                DATE = "${params.PARAMETER}"
            }
            steps {
                sh '''\
                echo hello
                '''
            }
        }

        stage('Archive TestCase') {
            steps {
                archiveArtifacts 'testcases/**/*'
            }
        }
    }

    post {
        success {
            echo "success"
        }

        failure {
            echo "failure"
        }
    }
}
