- name: "[Homedir] Create symlinks"
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .inputrc
    - .gitconfig
    - .tigrc
    - .config/fish/config.fish
    - .config/fish/functions/ghurls.fish
    - .tmux.conf
    - .gconf
    - .vimrc
    - .vim
    - .ideavimrc
    - .vim-snippets


- name: "[Homedir] Create profiles different for each target"
  file:
    src: '{{ ubuntu_mnt }}/.profile/{{ profile }}/{{ item }}'
    dest: ~/{{ item }}.profile
    state: link
  with_items:
    - config.fish
    - .tmux.conf


- name: "[Homedir] Create symlinks for VS Code"
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .config/Code/User/keybindings.json
    - .config/Code/User/settings.json
    - .config/Code/User/snippets
  when: env == "vm-gui"

- name: "[Homedir] Create IntelliJ IDEA symlinks"
  file:
    src: '~/{{ intellij_dir }}'
    dest: ~/.IntelliJIdea
    state: link
    force: yes

- name: "[Homedir] Create directories for IntelliJ IDEA"
  file:
    path: ~/.IntelliJIdea/{{ item }}
    state: directory
    mode: 0775
  with_items:
    - config/colors
    - config/keymaps
  when: env == "vm-gui"

- name: "[Homedir] Create symlinks for IntelliJ IDEA"
  file:
    src: '{{ ubuntu_mnt }}/.IntelliJIdea/{{ item }}'
    dest: ~/.IntelliJIdea/{{ item }}
    state: link
    force: yes
  with_items:
    - config/colors/mamansoft.icls
    - config/keymaps/mamansoft.xml
    - config/options/editor.xml
    - config/options/colors.scheme.xml
    - config/options/ide.general.xml
    - config/options/keymap.xml
    - config/options/markdown.xml
    - config/options/vcs.xml
    - config/options/vim_settings.xml
    - config/templates
  when: env == "vm-gui"

