- name: "[Homedir] Create symlinks"
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .inputrc
    - .gitconfig
    - .tigrc
    - .config/fish/config.fish
    - .config/fish/functions/ghurls.fish
    - .vim
    - .tmux.conf
    - .gconf
  tags: engsvr

- name: "[Homedir] Create symlinks without engsvr"
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
  with_items:
    - .vimrc

- name: "[Homedir] Create profiles different for each target"
  file:
    src: '{{ ubuntu_mnt }}/.profile/{{ profile }}/{{ item }}'
    dest: ~/{{ item }}.profile
    state: link
  with_items:
    - config.fish
    - .tmux.conf
  tags: engsvr

