- name: "[Homedir] Create symlinks"
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .inputrc
    - .gitconfig
    - .tigrc
    - .config/fish/config.fish
    - .config/fish/functions/ghurls.fish
    - .config/Code/User/keybindings.json
    - .config/Code/User/settings.json
    - .config/Code/User/snippets
    - .vim
    - .tmux.conf
    - .gconf
    - .vimrc

- name: "[Homedir] Create symlinks for IntelliJ IDEA"
  file:
    src: '{{ ubuntu_mnt }}/.IntelliJIdea/{{ item }}'
    dest: ~/{{ intellij_dir }}/{{ item }}
    state: link
    force: yes
  with_items:
    - config/colors/mamansoft.icls
    - config/keymaps/mamansoft.xml
    - config/options/editor.xml

- name: "[Homedir] Create profiles different for each target"
  file:
    src: '{{ ubuntu_mnt }}/.profile/{{ profile }}/{{ item }}'
    dest: ~/{{ item }}.profile
    state: link
  with_items:
    - config.fish
    - .tmux.conf

