- name: Create symlinks to files in home dir
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
  with_items:
    - .inputrc
    - .gitconfig
    - .tigrc
    - .config/fish/config.fish
  tags: engsvr

- name: Create symlinks to files in home dir (skip if engsvr)
  file:
    src: '{{ ubuntu_mnt }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
  with_items:
    - .vimrc

- name: Create profiles
  file:
    src: '{{ ubuntu_mnt }}/.profile/{{ profile }}/{{ item }}'
    dest: ~/{{ item }}.profile
    state: link
  with_items:
    - config.fish
  tags: engsvr

