#-----------------
# Markdown
#-----------------

[[plugins]]
# テーブルフォーマットに必要
repo = 'godlygeek/tabular'

[[plugins]]
# Markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
depends = ['tabular']
# リストインデントはスペース何コ分か
hook_add = 'let g:vim_markdown_new_list_item_indent = 2'


#-----------------
# Syntax
#-----------------

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

