- name: "Clone"
  git:
    repo: https://github.com/universal-ctags/ctags.git
    dest: /tmp/ctags
    depth: 1

- name: Install
  shell: "./autogen.sh && ./configure --prefix=/usr/local && make && make install"
  become: yes
  args:
    chdir: /tmp/ctags
