# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "tadashi-aikawa/lubuntu-jp"
  config.disksize.size = "40GB"

  # port forward
  [3000, 3001, 5432, 8000, 8888].each do |port|
    config.vm.network "forwarded_port", guest: port, host: port, host_ip: "127.0.0.1"
  end
  config.vm.network "private_network", ip: "192.168.33.10"

  # VirtualBox VM options
  config.vm.provider "virtualbox" do |vb|
    vb.name = "lubuntu-jp"
    vb.cpus = "2"
    vb.memory = "4096"
    # GUI settings
    vb.gui = true
    vb.customize [
      "modifyvm", :id,
      "--vram", "256",
      "--accelerate3d", "on",
      "--hwvirtex", "on",
      "--nestedpaging", "on",
      "--largepages", "on",
      "--ioapic", "on",
      "--pae", "on",
      "--paravirtprovider", "kvm",
      "--clipboard", "bidirectional",
      "--draganddrop", "bidirectional",
      "--monitorcount", "1",
      "--nictype1", "virtio",
      "--nictype2", "virtio",
      "--natdnshostresolver1", "on",
      "--uartmode1", "disconnected",
    ]
  end

  # sync
  config.vm.synced_folder "../../mnt", "/mnt"
  config.vm.synced_folder "../ansible", "/mnt-ansible"
  target_path = ENV['USERPROFILE'].gsub(/\\/,'/') + "/tmp"
  config.vm.synced_folder target_path, "/mnt-tmp"

  # Install docker
  config.vm.provision "docker"

  # Secret
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "file", source: "~/.gowlconfig", destination: ".gowlconfig"
  config.vm.provision "file", source: "~/.ssh", destination: ".ssh"

  # Install others
  config.vm.provision :shell, :path => "provision.sh"
end

