- name: "[Powerline] Clone font"
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/fonts
    depth: 1

- name: "[Powerline] Install"
  shell: ./install.sh
  args:
    chdir: /tmp/fonts

