- name: Create symlinks
  file:
    src: '{{ ubuntu_mnt }}/.bashrc'
    dest: ~/.bashrc.org
    state: link
    force: yes

- name: Add to loading .bashrc.org
  lineinfile:
    path: ~/.bashrc
    line: '. ~/.bashrc.org'

