---

- &base
  hosts: local
  connection: local
  vars:
    profile: vm-gui
  tasks:
    - group_by:
        key: '{{ env }}'


- name: "=============== 1. Core setup ==============="
  <<: *base
  roles:
    - role: core/env
    - role: core/curl
    - role: core/wget
    - role: core/make
    - role: core/ntp
    - role: core/cmigemo
    - role: core/git

- name: "=============== 2. Terminal setup ==============="
  <<: *base
  roles:
    - role: terminal/fish
    - role: terminal/fish/fisherman
    - role: terminal/fzf
    - role: terminal/tmux
    - role: terminal/tmux/theme

- name: "=============== 3. Package manager setup =============="
  <<: *base
  roles:
    - role: package_manager/umake
    - role: package_manager/npm
    - role: package_manager/pip2
    - role: package_manager/pip3

- name: "=============== 4. Font setup ==============="
  <<: *base
  roles:
    - role: font/powerline

- name: "=============== 5. Editor/IDE ==============="
  <<: *base
  roles:
    - role: editor/vim
    - role: editor/vim/dein
    - role: editor/neovim
    - role: editor/vscode
    - role: editor/idea

- name: "=============== 6. Language ==============="
  <<: *base
  roles:
    - role: language/bash/language_server
    - role: language/bash/shellcheck
    - role: language/go
    - role: language/haskell
    - role: language/python/python2
    - role: language/python/pyenv
    - role: language/python/pipenv

- name: "=============== 7. CLI tool ==============="
  <<: *base
  roles:
    - role: clitool/awscli
    - role: clitool/bat
    - role: clitool/bats
    - role: clitool/diff-so-fancy
    - role: clitool/docker-compose
    - role: clitool/exa
    - role: clitool/fd
    - role: clitool/glances
    - role: clitool/gowl
    - role: clitool/jq
    - role: clitool/ncdu
    - role: clitool/nkf
    - role: clitool/ripgrep
    - role: clitool/tig

- name: "=============== 8. Link ==============="
  <<: *base
  roles:
    - role: link/common
    - role: link/fish
    # - role: link/vscode
    # - role: link/idea


