- name: Install
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: /usr/bin/diff-so-fancy
    mode: u+x,g+x,o+x
