- name: Install
  unarchive:
    src: https://github.com/tadashi-aikawa/gowl/releases/download/v{{ gowl_version }}/gowl-{{ gowl_version }}-x86_64-linux.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install
  copy:
    src: /tmp/dist/linux/gowl
    dest: /usr/bin/gowl
    mode: 0755
