---

- &base
  hosts: local
  connection: local
  vars:
    ubuntu_mnt: ~/owl-playbook/mnt/linux/ubuntu
    common_mnt: ~/owl-playbook/mnt/common


- name: "=============== 1. Core setup ==============="
  <<: *base
  roles:
    - role: core/env
    - role: core/curl
    - role: core/wget
    - role: core/make
    - role: core/ntp

- name: "=============== 2. Terminal setup ==============="
  <<: *base
  roles:
    - role: link/bash
    - role: link/input
    - role: terminal/pureline-inspired
    - role: terminal/fzf
    - role: terminal/tmux
    - role: terminal/tmux/theme
    - role: link/tmux

- name: "=============== 3. Package manager setup =============="
  <<: *base
  roles:
    - role: package_manager/npm

- name: "=============== 4. Editor/IDE ==============="
  <<: *base
  roles:
    - role: editor/vim
    - role: editor/vim/dein
    - role: editor/neovim
    - role: link/vim

- name: "=============== 5. Language ==============="
  <<: *base
  roles:
    - role: language/bash/language_server
    - role: language/bash/shellcheck
    - role: language/python/pyenv
    - role: language/python/poetry

- name: "=============== 6. CLI tool ==============="
  <<: *base
  roles:
    - role: clitool/awscli
    - role: clitool/bat
    - role: clitool/bats
    - role: clitool/ctags
    - role: clitool/diff-so-fancy
    - role: clitool/docui
    - role: clitool/docker-compose
    - role: clitool/exa
    - role: clitool/fd
    - role: clitool/fx
    - role: clitool/glances
    - role: clitool/gowl
    - role: clitool/jq
    - role: clitool/ncdu
    - role: clitool/nkf
    - role: clitool/ripgrep
    - role: clitool/tig
    - role: link/tig
    - role: clitool/tree
    - role: clitool/xclip
    - role: clitool/zstd
    - role: clitool/z

