- name: Create directories for links
  file:
    path: ~/.config/Code/User
    state: directory
    mode: 0775

- name: Create symlinks
  file:
    src: '{{ common_mnt }}/VSCode/User/{{ item }}'
    dest: ~/.config/Code/User/{{ item }}
    state: link
    force: yes
  with_items:
    - keybindings.json
    - settings.json
    - snippets
