- name: Install
  unarchive:
    src: https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-v{{ bat_version }}-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install
  shell: mv bat-v{{ bat_version }}-x86_64-unknown-linux-musl/bat /usr/bin/bat
  args:
    chdir: /tmp
